# Generated by Django 6.0.6 on 2026-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('it', 'IT Personnel'), ('admin', 'Administrator')], default='it', max_length=20),
        ),
    ]
